services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:7
  api:
    build: ../backend
    depends_on:
      - db
      - redis
      - model-service
    environment:
      DATABASE_URL: postgresql://user:pass@db:5432/bank
      CELERY_BROKER_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
  model-service:
    build: ../model-service
    volumes:
      - ../model.pkl:/models/model.pkl
    ports:
      - "8001:8000"
  frontend:
    build: ../frontend
    ports:
      - "8080:80"
  celery:
    build: ../backend
    command: python celery_worker.py
    depends_on:
      - redis
volumes:
  db-data: